# Generated by Django 5.2.5 on 2025-08-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_employee', '0001_initial'),
        ('app_quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateInvoiceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_invoice_number', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=20, unique=True, verbose_name='ລະຫັດໃບເກັບເງິນ')),
                ('issue_date', models.DateField(verbose_name='ວັນທີອອກໃບເກັບເງິນ')),
                ('due_date', models.DateField(verbose_name='ວັນທີຫມົດອາຍຸ')),
                ('status', models.CharField(choices=[('pending', 'ກຳລັງລໍຖ້າ'), ('unpaid', 'ຍັງບໍ່ໄດ້ຈ່າຍ'), ('paid', 'ຈ່າຍແລ້ວ'), ('rejected', 'ປະຕິເສດ'), ('cancelled', 'ຍົກເລີກ')], default='pending', max_length=20, verbose_name='ສະຖານະ')),
                ('invoice_signatured', models.FileField(blank=True, null=True, upload_to='invoice_docs/', verbose_name='ໃບເກັບເງິນທີ່ຮັບຮອງແລ້ວ ຫລື ໃບສັ່ງຊື້ຈາກລູກຄ້າ')),
                ('customer_payment', models.FileField(blank=True, null=True, upload_to='invoice_docs/', verbose_name='ຫລັກຖານການຈ່າຍເງິນຂອງລູກຄ້າ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_employee.employeesmodel', verbose_name='ພະນັກງານຮັບຜິດຊອບ')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='app_quotations.quotationinformationmodel', verbose_name='ໃບສະເຫນີລາຄາ')),
            ],
            options={
                'verbose_name': 'ການຈັດການ ໃບເກັບເງິນ',
                'verbose_name_plural': 'ການຈັດການ ໃບເກັບເງິນ',
                'ordering': ['-due_date'],
            },
        ),
    ]
