# Generated by Django 5.2.5 on 2025-08-21 01:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customers', '0001_initial'),
        ('app_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateQuotationID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qotation_id_generator', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationInformationModel',
            fields=[
                ('created_at_log', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ວັນເວລາສ້າງ')),
                ('updated_at_log', models.DateTimeField(auto_now=True, verbose_name='ວັນທີອັບເດດຂໍ້ມູນ')),
                ('status', models.CharField(choices=[('pending', 'ລໍຖ້າອະນຸມັດ'), ('completed', 'ສຳເລັດ'), ('rejected', 'ປະຕິເສດ'), ('cancelled', 'ຍົກເລີກ'), ('banned', 'ຖືກລະງັບ')], default='pending', max_length=20, verbose_name='ສະຖານະ')),
                ('total_all_products', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, null=True, verbose_name='ລາຄາລວມທັງໝົດ')),
                ('quotation_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='ວັນທີອອກ')),
                ('end_date', models.DateField(verbose_name='ວັນທີ່ສິ້ນສຸດ')),
                ('upload_signatured_quo', models.FileField(blank=True, null=True, upload_to='quotation_docs/', verbose_name='ໃບສະເຫນີລາຄາທີ່ເຊັນຮັບຮອງແລ້ວ')),
                ('customer_po', models.FileField(blank=True, null=True, upload_to='quotation_docs/', verbose_name='ໃບສັ່ງຊື້ຂອງລູກຄ້າ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='app_employee.employeesmodel', verbose_name='ສ້າງໂດຍ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='app_customers.customersmodel', verbose_name='ລູກຄ້າ')),
            ],
            options={
                'verbose_name': 'ໃບສະເຫນີລາຄາ',
                'verbose_name_plural': 'ໃບສະເຫນີລາຄາ',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalExpensesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_all_product_ref', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, null=True, verbose_name='ລາຄາລວມທັງໝົດ')),
                ('it_service_percent', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, verbose_name='ຄ່າບໍລິການ IT (%)')),
                ('it_service_output', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, null=True, verbose_name='ລາຄາບໍລິການ IT')),
                ('vat_percent', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, verbose_name='VAT (%)')),
                ('vat_output', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, null=True, verbose_name='VAT')),
                ('exchange_rate', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='ອັດຕາແລກປ່ຽນ')),
                ('exchange_rate_output', models.DecimalField(blank=True, decimal_places=0, default=Decimal('0'), editable=False, max_digits=20, null=True, verbose_name='ອັດຕາແລກປ່ຽນ (ກິບ)')),
                ('grand_total', models.DecimalField(blank=True, decimal_places=0, default=Decimal('0.00'), editable=False, max_digits=20, null=True, verbose_name='ລາຄາລວມທັງໝົດ (ທັງໝົດ)')),
                ('common_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_payments', to='app_quotations.quotationinformationmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='ຊື່ສິນຄ້າ')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ລາຄາ')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='ຈຳນວນ')),
                ('period', models.PositiveIntegerField(default=12, verbose_name='ລະດັບເວລາ (ເດືອນ)')),
                ('total_one_product', models.DecimalField(blank=True, decimal_places=2, default=Decimal('1'), editable=False, max_digits=10, null=True, verbose_name='ລາຄາລວມ')),
                ('common_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_quotations.quotationinformationmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
