# Generated by Django 5.2.5 on 2025-08-21 01:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesModel',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_lastname', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('signature', models.ImageField(upload_to='employee_signatures')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ຂໍ້ມູນພະນັກງານ',
                'verbose_name_plural': 'ຂໍ້ມູນພະນັກງານ',
                'ordering': ('employee_id',),
            },
        ),
    ]
